- hosts: all
  tasks:
   - package:
        name: python3
        state: present

   - pip:
        name: docker==4.4.1
        state: present

   - docker_image:
        name: httpd
        source: pull   
  
   - file:
        state: directory
        path: "/home/mounted"

   - copy:
        src: "/root/dockerWeb/code.html"
        dest: "/home/mounted"

   - docker_container:
        name: webserverOS
        image: httpd
        state: started
        ports: 
           - "8080:80"
        mounts:
          - source: "/home/mounted"
            target: "/usr/local/apache2/htdocs"
            type: bind
            read_only: no
            propagation: rprivate
